name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build --if-present
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.HOST_SSH_KEY }}
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          script: |
            pm2 stop cardinal-bot
            cd /root/cardinal-bot
            git pull
            yarn install --frozen-lockfile
            yarn build
            yarn prisma:push-prod
            pm2 start NODE_ENV=production dist/index.js --name cardinal-bot
